### ISSUE TITLE
Crash: Perpetuum Mobile on How to Poke At Slimes

### ISSUE THREAD

**Issue by Skrelpoid** [jonasdasdefekte/The-Sage#15]
```
Exception: java.lang.NullPointerException
23:17:31.381 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
    at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:24) ~[desktop-1.0.jar:?]
    at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:37) ~[desktop-1.0.jar:?]
    at sagemod.cards.AbstractSageCard.attackAllEnemies(AbstractSageCard.java:168) ~[SageMod.jar:?]
    at sagemod.cards.AbstractSageCard.attackAllEnemies(AbstractSageCard.java:163) ~[SageMod.jar:?]
    at sagemod.cards.HowToPokeAtSlimes.use(HowToPokeAtSlimes.java:59) ~[SageMod.jar:?]
    at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
    at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
    at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
    at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:159) ~[?:?]
    at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:283) ~[?:?]
    at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2531) ~[?:?]
    at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
    at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435) [?:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
```

**Comment by Skrelpoid** [comment]
Fixed by setting isMultidamage = true
