### ISSUE TITLE
Crash from picking up Cabbage Head relic

### ISSUE THREAD

**Issue by jonasdasdefekte** [jonasdasdefekte/The-Sage#35]
(Bug from Steam Workshop comments)

**Comment by Skrelpoid** [comment]
Reason for this is that it tries to apply the dexterity Power, even when not in a fight.

Stacktrace:
```
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-22-2020)
 - ModTheSpire (3.23.2)
Mod list:
 - basemod (5.33.1)
 - stslib (1.24.1)
 - sagemod (0.5.1)

Cause:
java.lang.NullPointerException
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.<init>(ApplyPowerAction.java:102)
	at com.megacrit.cardcrawl.actions.common.ApplyPowerAction.<init>(ApplyPowerAction.java:127)
	at sagemod.relics.AbstractSageRelic.applyPower(AbstractSageRelic.java:39)
	at sagemod.relics.AbstractSageRelic.applyPowerToSelf(AbstractSageRelic.java:34)
	at sagemod.relics.CabbageHead.gainDexterity(CabbageHead.java:29)
	at sagemod.relics.CabbageHead.onEquip(CabbageHead.java:24)
	at com.megacrit.cardcrawl.relics.AbstractRelic.update(AbstractRelic.java:388)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.updateObjects(AbstractRoom.java:241)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2518)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:871)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```
